export const airports = [
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport, Atlanta" },
  { code: "PEK", name: "Beijing Capital International Airport, Beijing" },
  { code: "LHR", name: "London Heathrow Airport, London" },
  { code: "ORD", name: "O'Hare International Airport, Chicago" },
  { code: "HND", name: "Tokyo Haneda Airport, Tokyo" },
  { code: "LAX", name: "Los Angeles International Airport, Los Angeles" },
  { code: "CDG", name: "Charles de Gaulle Airport, Paris" },
  { code: "DFW", name: "Dallas/Fort Worth International Airport, Dallas" },
  { code: "FRA", name: "Frankfurt Airport, Frankfurt" },
  { code: "HKG", name: "Hong Kong International Airport, Hong Kong" },
  { code: "DXB", name: "Dubai International Airport, Dubai" },
  { code: "CGK", name: "Soekarno-Hatta International Airport, Jakarta" },
  { code: "AMS", name: "Amsterdam Airport Schiphol, Amsterdam" },
  { code: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport, Madrid" },
  { code: "BKK", name: "Suvarnabhumi Airport, Bangkok" },
  { code: "JFK", name: "John F. Kennedy International Airport, New York" },
  { code: "SIN", name: "Singapore Changi Airport, Singapore" },
  { code: "CAN", name: "Guangzhou Baiyun International Airport, Guangzhou" },
  { code: "LAS", name: "McCarran International Airport, Las Vegas" },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport, Rome" },
  { code: "YYZ", name: "Toronto Pearson International Airport, Toronto" },
  { code: "SFO", name: "San Francisco International Airport, San Francisco" },
  { code: "MIA", name: "Miami International Airport, Miami" },
  { code: "SYD", name: "Sydney Airport, Sydney" },
  { code: "MUC", name: "Munich Airport, Munich" },
  { code: "DEL", name: "Indira Gandhi International Airport, Delhi" },
  { code: "BCN", name: "Barcelona–El Prat Airport, Barcelona" },
  { code: "LGW", name: "London Gatwick Airport, London" },
  { code: "SEA", name: "Seattle-Tacoma International Airport, Seattle" },
  { code: "ICN", name: "Incheon International Airport, Seoul" },
  { code: "MEX", name: "Mexico City International Airport, Mexico City" },
  { code: "KUL", name: "Kuala Lumpur International Airport, Kuala Lumpur" },
  { code: "IST", name: "Istanbul Airport, Istanbul" },
  { code: "MNL", name: "Ninoy Aquino International Airport, Manila" },
  { code: "CTU", name: "Chengdu Shuangliu International Airport, Chengdu" },
  { code: "DME", name: "Domodedovo International Airport, Moscow" },
  { code: "SVO", name: "Sheremetyevo International Airport, Moscow" },
  { code: "BOM", name: "Chhatrapati Shivaji International Airport, Mumbai" },
  { code: "DEN", name: "Denver International Airport, Denver" },
  { code: "BOS", name: "Boston Logan International Airport, Boston" },
  { code: "NRT", name: "Narita International Airport, Tokyo" },
  { code: "DUS", name: "Düsseldorf Airport, Düsseldorf" },
  { code: "ARN", name: "Stockholm Arlanda Airport, Stockholm" },
  { code: "CPH", name: "Copenhagen Airport, Copenhagen" },
  { code: "VIE", name: "Vienna International Airport, Vienna" },
  { code: "TPE", name: "Taiwan Taoyuan International Airport, Taipei" },
  { code: "ZRH", name: "Zürich Airport, Zürich" },
  { code: "YVR", name: "Vancouver International Airport, Vancouver" },
  { code: "JNB", name: "O. R. Tambo International Airport, Johannesburg" },
  { code: "HEL", name: "Helsinki Airport, Helsinki" }
];
